export const ShopActionTypes = {
    FETCH_SHOPCOLLECTION_START: 'FETCH_SHOPCOLLECTION_START',
    FETCH_SHOPCOLLECTION_SUCCESS: 'FETCH_SHOPCOLLECTION_SUCCESS',
    FETCH_SHOPCOLLECTION_FAILURE: 'FETCH_SHOPCOLLECTION_FAILURE'
}